#!/usr/bin/expect -f
set timeout 3600
spawn ssh GrupsBunny@192.168.1.173
expect "password:"
send "32215820\r"
expect "GrupsBunny@ZimaOS"
send "cd /DATA/AppData/openjarvis-app && sudo env DOCKER_CONFIG=/DATA/AppData/.docker-user /DATA/AppData/.docker-user/cli-plugins/docker-compose up -d --build --force-recreate\r"
expect "Password:"
send "32215820\r"
expect "GrupsBunny@ZimaOS"
send "exit\r"
expect eof
